import os
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from models import Base, Property, User
from security import hash_password
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./properties.db")

if DATABASE_URL.startswith("sqlite"):
    engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False})
else:
    engine = create_engine(DATABASE_URL)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

DEFAULT_ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", "admin@propsearch.com")
DEFAULT_ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD", "admin123")

def init_db():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        admin = db.query(User).filter(User.email == DEFAULT_ADMIN_EMAIL).first()
        if not admin:
            admin = User(
                name="Site Admin",
                email=DEFAULT_ADMIN_EMAIL,
                hashed_password=hash_password(DEFAULT_ADMIN_PASSWORD),
                role="admin",
            )
            db.add(admin)
            db.commit()
            db.refresh(admin)
            print(f"Created default admin account: {DEFAULT_ADMIN_EMAIL} / {DEFAULT_ADMIN_PASSWORD}")

        if db.query(Property).count() == 0:
            print("Seeding properties database...")
            mock_properties = [
                # --- BANGALORE PROPERTIES ---
                Property(
                    title="Cozy 2 BHK Apartment in Koramangala",
                    city="Bangalore",
                    locality="Koramangala",
                    price=35000,
                    type="rent",
                    property_type="flat",
                    bhk=2,
                    bathrooms=2,
                    area=1100,
                    image_filename="cozy_flat_interior.png",
                    description="Beautiful, semi-furnished 2 BHK apartment in the heart of Koramangala. Close to premium restaurants, cafes, and tech parks. Offers round-the-clock water, security, and power backup.",
                    amenities="Parking, Security, Power Backup, Gym, Elevator",
                    agent_name="Amit Kumar",
                    agent_phone="+91 98765 43210",
                    agent_email="amit.kumar@propsearch.com"
                ),
                Property(
                    title="Luxury 4 BHK Villa in Whitefield",
                    city="Bangalore",
                    locality="Whitefield",
                    price=120000,
                    type="rent",
                    property_type="house",
                    bhk=4,
                    bathrooms=4,
                    area=3500,
                    image_filename="modern_villa_bangalore.png",
                    description="Stunning 4 BHK independent villa in a secure gated community in Whitefield. Features a private garden, modular kitchen, large balconies, and high-end fittings.",
                    amenities="Private Garden, Pool, Gym, Club House, 24x7 Security, Pet Friendly",
                    agent_name="Rajesh Sharma",
                    agent_phone="+91 98765 43211",
                    agent_email="rajesh.sharma@propsearch.com"
                ),
                Property(
                    title="Modern 1 BHK Studio Flat in Indiranagar",
                    city="Bangalore",
                    locality="Indiranagar",
                    price=22000,
                    type="rent",
                    property_type="flat",
                    bhk=1,
                    bathrooms=1,
                    area=600,
                    image_filename="cozy_flat_interior.png",
                    description="Sleek and minimalist 1 BHK studio flat ideal for working professionals. Steps away from Indiranagar Metro Station and 100 Feet Road. Fully air-conditioned.",
                    amenities="Parking, Lift, Security, Power Backup, AC",
                    agent_name="Amit Kumar",
                    agent_phone="+91 98765 43210",
                    agent_email="amit.kumar@propsearch.com"
                ),
                Property(
                    title="Semi-Furnished 3 BHK House in HSR Layout",
                    city="Bangalore",
                    locality="HSR Layout",
                    price=55000,
                    type="rent",
                    property_type="house",
                    bhk=3,
                    bathrooms=3,
                    area=1800,
                    image_filename="modern_villa_bangalore.png",
                    description="Spacious independent 3 BHK house in Sector 3, HSR Layout. Excellent ventilation, overhead water tank, dedicated car parking space, and private terrace access.",
                    amenities="Terrace, Car Parking, Pet Friendly, Security, Water Storage",
                    agent_name="Priya Nair",
                    agent_phone="+91 98765 43212",
                    agent_email="priya.nair@propsearch.com"
                ),
                Property(
                    title="Premium 3 BHK Penthouse in Jayanagar",
                    city="Bangalore",
                    locality="Jayanagar",
                    price=85000,
                    type="rent",
                    property_type="flat",
                    bhk=3,
                    bathrooms=3,
                    area=2200,
                    image_filename="luxury_penthouse.png",
                    description="Luxurious penthouse with an expansive private terrace overlooking the green canopy of Jayanagar. Equipped with premium fittings, Italian marble flooring, and smart-home controls.",
                    amenities="Balcony View, Gym, Lift, Clubhouse, Pool, Private Terrace",
                    agent_name="Priya Nair",
                    agent_phone="+91 98765 43212",
                    agent_email="priya.nair@propsearch.com"
                ),
                Property(
                    title="Elegant 2 BHK Apartment in HSR Layout",
                    city="Bangalore",
                    locality="HSR Layout",
                    price=7800000,
                    type="buy",
                    property_type="flat",
                    bhk=2,
                    bathrooms=2,
                    area=1250,
                    image_filename="cozy_flat_interior.png",
                    description="Modern 2 BHK apartment up for sale in a newly constructed society in HSR Layout. Features modular wardrobes, false ceilings, and vastu-compliant design.",
                    amenities="Parking, Lift, Power Backup, Kids Play Area, CCTV, Gym",
                    agent_name="Kiran Gowda",
                    agent_phone="+91 98765 43213",
                    agent_email="kiran.gowda@propsearch.com"
                ),
                Property(
                    title="Spacious 4 BHK Independent Villa in Sarjapur",
                    city="Bangalore",
                    locality="Sarjapur Road",
                    price=32500000,
                    type="buy",
                    property_type="house",
                    bhk=4,
                    bathrooms=4,
                    area=3800,
                    image_filename="modern_villa_bangalore.png",
                    description="Ultra-luxury 4 BHK triplex villa with a private lawn and pool. Located in a high-end township on Sarjapur Road. Premium woodwork and luxury sanitaryware included.",
                    amenities="Private Pool, Private Lawn, Home Automation, Gym, Tennis Court, Security",
                    agent_name="Kiran Gowda",
                    agent_phone="+91 98765 43213",
                    agent_email="kiran.gowda@propsearch.com"
                ),
                Property(
                    title="Ultra Luxury 3 BHK Flat in Indiranagar",
                    city="Bangalore",
                    locality="Indiranagar",
                    price=21000000,
                    type="buy",
                    property_type="flat",
                    bhk=3,
                    bathrooms=3,
                    area=2100,
                    image_filename="luxury_apartment_mumbai.png",
                    description="Premium high-rise apartment in Indiranagar. Large wrap-around balcony, master suite with walk-in closet, imported modular kitchen, and luxury wellness facilities.",
                    amenities="Pool, Gym, Lift, 24x7 Security, Intercom, Club Lounge, Car Wash Bay",
                    agent_name="Rajesh Sharma",
                    agent_phone="+91 98765 43211",
                    agent_email="rajesh.sharma@propsearch.com"
                ),
                Property(
                    title="Beautiful 3 BHK Row House in Whitefield",
                    city="Bangalore",
                    locality="Whitefield",
                    price=16500000,
                    type="buy",
                    property_type="house",
                    bhk=3,
                    bathrooms=3,
                    area=2400,
                    image_filename="modern_villa_bangalore.png",
                    description="Corner row-house with 3 bedrooms and a study. Located close to Hope Farm Junction, Whitefield. Has dedicated covered parking for two vehicles and a small front yard.",
                    amenities="Security, Power Backup, Gym, Clubhouse, Covered Parking, Play Area",
                    agent_name="Rajesh Sharma",
                    agent_phone="+91 98765 43211",
                    agent_email="rajesh.sharma@propsearch.com"
                ),
                Property(
                    title="Charming 1 BHK Flat in Electronic City",
                    city="Bangalore",
                    locality="Electronic City Phase 1",
                    price=4200000,
                    type="buy",
                    property_type="flat",
                    bhk=1,
                    bathrooms=1,
                    area=650,
                    image_filename="cozy_flat_interior.png",
                    description="Affordable and compact 1 BHK flat perfect for first-time buyers or investors. Located in Phase 1 of Electronic City, near major IT campus hubs.",
                    amenities="Parking, Lift, Security, Jogging Track, Rainwater Harvesting",
                    agent_name="Amit Kumar",
                    agent_phone="+91 98765 43210",
                    agent_email="amit.kumar@propsearch.com"
                ),
                Property(
                    title="Modern 3 BHK Apartment in Yelahanka",
                    city="Bangalore",
                    locality="Yelahanka",
                    price=32000,
                    type="rent",
                    property_type="flat",
                    bhk=3,
                    bathrooms=3,
                    area=1600,
                    image_filename="cozy_flat_interior.png",
                    description="Spacious 3 BHK apartment in a serene gated society in Yelahanka. Excellent views, dedicated parking, and premium amenities included.",
                    amenities="Parking, Lift, Security, Clubhouse, Gym",
                    agent_name="Amit Kumar",
                    agent_phone="+91 98765 43210",
                    agent_email="amit.kumar@propsearch.com"
                ),
                Property(
                    title="Sleek 1 BHK Flat in Bellandur",
                    city="Bangalore",
                    locality="Bellandur",
                    price=28000,
                    type="rent",
                    property_type="flat",
                    bhk=1,
                    bathrooms=1,
                    area=700,
                    image_filename="cozy_flat_interior.png",
                    description="Compact and modern 1 BHK flat in Bellandur. Very close to major tech parks (Ecospace). Fully semi-furnished with cupboards.",
                    amenities="Parking, Security, Power Backup, Elevator",
                    agent_name="Priya Nair",
                    agent_phone="+91 98765 43212",
                    agent_email="priya.nair@propsearch.com"
                ),
                Property(
                    title="Spacious 2 BHK Flat in Hebbal",
                    city="Bangalore",
                    locality="Hebbal",
                    price=45000,
                    type="rent",
                    property_type="flat",
                    bhk=2,
                    bathrooms=2,
                    area=1200,
                    image_filename="luxury_apartment_mumbai.png",
                    description="Beautiful high-rise 2 BHK flat near Hebbal Flyover. Has a spacious balcony, modern kitchen setup, and top-tier security.",
                    amenities="Parking, Lift, Security, Pool, Gym, Power Backup",
                    agent_name="Rajesh Sharma",
                    agent_phone="+91 98765 43211",
                    agent_email="rajesh.sharma@propsearch.com"
                ),
                Property(
                    title="Charming 3 BHK House in Banashankari",
                    city="Bangalore",
                    locality="Banashankari",
                    price=40000,
                    type="rent",
                    property_type="house",
                    bhk=3,
                    bathrooms=2,
                    area=1600,
                    image_filename="modern_villa_bangalore.png",
                    description="Independent 3 BHK house located in a quiet residential area in Banashankari. Private parking space and overhead water tank.",
                    amenities="Car Parking, Water Storage, Terrace access, Pet Friendly",
                    agent_name="Kiran Gowda",
                    agent_phone="+91 98765 43213",
                    agent_email="kiran.gowda@propsearch.com"
                ),
                Property(
                    title="Premium 3 BHK Flat on Kanakapura Road",
                    city="Bangalore",
                    locality="Kanakapura Road",
                    price=11000000,
                    type="buy",
                    property_type="flat",
                    bhk=3,
                    bathrooms=3,
                    area=1550,
                    image_filename="luxury_apartment_mumbai.png",
                    description="Ready-to-move-in vastu-compliant 3 BHK flat. Premium fixtures, wood flooring in master bedroom, and spacious balcony views.",
                    amenities="Parking, Lift, Security, Gym, Swimming Pool, Clubhouse",
                    agent_name="Kiran Gowda",
                    agent_phone="+91 98765 43213",
                    agent_email="kiran.gowda@propsearch.com"
                ),
                Property(
                    title="Cozy 2 BHK Flat in Electronic City",
                    city="Bangalore",
                    locality="Electronic City Phase 2",
                    price=5200000,
                    type="buy",
                    property_type="flat",
                    bhk=2,
                    bathrooms=2,
                    area=1050,
                    image_filename="cozy_flat_interior.png",
                    description="Great 2 BHK apartment for IT professionals. Located close to tech offices. Semi-furnished with wardrobes.",
                    amenities="Parking, Security, Power Backup, Elevator, CCTV",
                    agent_name="Amit Kumar",
                    agent_phone="+91 98765 43210",
                    agent_email="amit.kumar@propsearch.com"
                ),
                Property(
                    title="Luxury 4 BHK Penthouse in Rajajinagar",
                    city="Bangalore",
                    locality="Rajajinagar",
                    price=28000000,
                    type="buy",
                    property_type="flat",
                    bhk=4,
                    bathrooms=4,
                    area=3000,
                    image_filename="luxury_penthouse.png",
                    description="Exclusive 4 BHK penthouse flat with panoramic views of Bangalore skyline. Premium Italian marble and modular kitchen.",
                    amenities="Balcony View, Private Terrace, Lift, Gym, Pool, Clubhouse, 24x7 Security",
                    agent_name="Priya Nair",
                    agent_phone="+91 98765 43212",
                    agent_email="priya.nair@propsearch.com"
                ),
                Property(
                    title="Premium 3 BHK Row House in Sarjapur",
                    city="Bangalore",
                    locality="Sarjapur Road",
                    price=13500000,
                    type="buy",
                    property_type="house",
                    bhk=3,
                    bathrooms=3,
                    area=2100,
                    image_filename="modern_villa_bangalore.png",
                    description="Stunning row house in a green, peaceful gated community. Private parking and backyard garden included.",
                    amenities="Security, Covered Parking, Gym, Playground, Power Backup",
                    agent_name="Rajesh Sharma",
                    agent_phone="+91 98765 43211",
                    agent_email="rajesh.sharma@propsearch.com"
                ),
                Property(
                    title="Modern 4 BHK Villa in Devanahalli",
                    city="Bangalore",
                    locality="Devanahalli",
                    price=24500000,
                    type="buy",
                    property_type="house",
                    bhk=4,
                    bathrooms=4,
                    area=2900,
                    image_filename="modern_villa_bangalore.png",
                    description="Elegant villa located near Bangalore International Airport. Private lawn, modern open kitchen layout, and spacious balconies.",
                    amenities="Private Garden, Parking, Security, Power Backup, Gym, Pool",
                    agent_name="Kiran Gowda",
                    agent_phone="+91 98765 43213",
                    agent_email="kiran.gowda@propsearch.com"
                ),
                Property(
                    title="Minimalist 1 BHK Flat in Manyata Tech Park",
                    city="Bangalore",
                    locality="Hebbal",
                    price=3800000,
                    type="buy",
                    property_type="flat",
                    bhk=1,
                    bathrooms=1,
                    area=550,
                    image_filename="cozy_flat_interior.png",
                    description="Compact and stylish studio flat inside Hebbal gated project. Super convenient for IT professionals working nearby.",
                    amenities="Parking, Lift, Security, Power Backup, Gym",
                    agent_name="Amit Kumar",
                    agent_phone="+91 98765 43210",
                    agent_email="amit.kumar@propsearch.com"
                ),

                # --- MUMBAI PROPERTIES ---
                Property(
                    title="High-rise 2 BHK Flat in Bandra West",
                    city="Mumbai",
                    locality="Bandra West",
                    price=95000,
                    type="rent",
                    property_type="flat",
                    bhk=2,
                    bathrooms=2,
                    area=1000,
                    image_filename="luxury_apartment_mumbai.png",
                    description="Exquisite sea-view 2 BHK flat on Carter Road, Bandra West. Modern interiors, high ceilings, large windows, and immediate access to the promenade.",
                    amenities="Sea View, Gym, Parking, Lift, 24x7 Security, Intercom, AC",
                    agent_name="Vikram Mehta",
                    agent_phone="+91 98200 12345",
                    agent_email="vikram.mehta@propsearch.com"
                ),
                Property(
                    title="Charming 3 BHK Row House in Powai",
                    city="Mumbai",
                    locality="Powai",
                    price=110000,
                    type="rent",
                    property_type="house",
                    bhk=3,
                    bathrooms=3,
                    area=2200,
                    image_filename="modern_villa_bangalore.png",
                    description="Rare independent row house in a green, peaceful pocket of Hiranandani Powai. Split levels, modular kitchen, and beautiful private terrace terrace.",
                    amenities="Private Terrace, Garden, Security, Gym, Gas Pipeline",
                    agent_name="Neha Shah",
                    agent_phone="+91 98200 12346",
                    agent_email="neha.shah@propsearch.com"
                ),
                Property(
                    title="Compact 1 BHK Flat in Andheri East",
                    city="Mumbai",
                    locality="Andheri East",
                    price=35000,
                    type="rent",
                    property_type="flat",
                    bhk=1,
                    bathrooms=1,
                    area=550,
                    image_filename="cozy_flat_interior.png",
                    description="Nicely maintained, fully-furnished 1 BHK apartment close to the metro station and Western Express Highway. Ideal for corporate executives.",
                    amenities="Parking, Lift, Security, CCTV, Internet, Gas Pipeline",
                    agent_name="Vikram Mehta",
                    agent_phone="+91 98200 12345",
                    agent_email="vikram.mehta@propsearch.com"
                ),
                Property(
                    title="Premium 4 BHK Villa in Juhu",
                    city="Mumbai",
                    locality="Juhu",
                    price=250000,
                    type="rent",
                    property_type="house",
                    bhk=4,
                    bathrooms=4,
                    area=4000,
                    image_filename="modern_villa_bangalore.png",
                    description="Ultra-premium 4 BHK independent bungalow close to Juhu Beach. Private compound, servant quarters, massive bedrooms, and private security post.",
                    amenities="Private Lawn, Swimming Pool, Beach Access, Parking, Servant Quarter",
                    agent_name="Rohan Joshi",
                    agent_phone="+91 98200 12347",
                    agent_email="rohan.joshi@propsearch.com"
                ),
                Property(
                    title="Luxury 3 BHK Penthouse in Worli",
                    city="Mumbai",
                    locality="Worli",
                    price=180000,
                    type="rent",
                    property_type="flat",
                    bhk=3,
                    bathrooms=3,
                    area=2600,
                    image_filename="luxury_penthouse.png",
                    description="Stunning penthouse flat overlooking the Bandra-Worli Sea Link. High ceiling layout, bespoke Italian furniture, wrap-around balcony, and world-class building amenities.",
                    amenities="Skyline View, Sea Link View, Gym, Pool, Security, Intercom, Concierge",
                    agent_name="Neha Shah",
                    agent_phone="+91 98200 12346",
                    agent_email="neha.shah@propsearch.com"
                ),
                Property(
                    title="Modern 2 BHK Flat in Powai",
                    city="Mumbai",
                    locality="Powai",
                    price=18500000,
                    type="buy",
                    property_type="flat",
                    bhk=2,
                    bathrooms=2,
                    area=1100,
                    image_filename="luxury_apartment_mumbai.png",
                    description="Beautiful lake-view 2 BHK flat inside Hiranandani Gardens, Powai. Completely vastu-compliant, premium wood flooring in master bedroom, and state-of-the-art kitchen.",
                    amenities="Lake View, Gym, Pool, Clubhouse, 24x7 Security, Covered Parking",
                    agent_name="Neha Shah",
                    agent_phone="+91 98200 12346",
                    agent_email="neha.shah@propsearch.com"
                ),
                Property(
                    title="Exclusive 4 BHK Bungalow in Chembur",
                    city="Mumbai",
                    locality="Chembur",
                    price=65000000,
                    type="buy",
                    property_type="house",
                    bhk=4,
                    bathrooms=4,
                    area=3600,
                    image_filename="modern_villa_bangalore.png",
                    description="Prestige bungalow in a residential colony of Chembur. Landscaped lawns, wooden decks, modular modular kitchen, and automated parking system for three SUVs.",
                    amenities="Private Garden, Multi-car Parking, Security, Power Backup, Water Harvest",
                    agent_name="Rohan Joshi",
                    agent_phone="+91 98200 12347",
                    agent_email="rohan.joshi@propsearch.com"
                ),
                Property(
                    title="Ultra-Premium 3 BHK Flat in Bandra West",
                    city="Mumbai",
                    locality="Bandra West",
                    price=48000000,
                    type="buy",
                    property_type="flat",
                    bhk=3,
                    bathrooms=3,
                    area=1800,
                    image_filename="luxury_apartment_mumbai.png",
                    description="Stunning luxury property situated off Pali Hill. Multi-level security, spacious balconies, master bathroom with jacuzzi, and high-performance noise-reduction windows.",
                    amenities="Gym, Lift, Concierge Service, Intercom, Parking, Automated Security",
                    agent_name="Vikram Mehta",
                    agent_phone="+91 98200 12345",
                    agent_email="vikram.mehta@propsearch.com"
                ),
                Property(
                    title="Sleek 1 BHK Apartment in Malad West",
                    city="Mumbai",
                    locality="Malad West",
                    price=9500000,
                    type="buy",
                    property_type="flat",
                    bhk=1,
                    bathrooms=1,
                    area=600,
                    image_filename="cozy_flat_interior.png",
                    description="Modern, smart-designed 1 BHK flat in Malad. Features optimal space usage, modular kitchen, close connection to shopping malls and Link Road.",
                    amenities="Parking, Lift, Gym, Security, Intercom, Kids Play Zone",
                    agent_name="Rohan Joshi",
                    agent_phone="+91 98200 12347",
                    agent_email="rohan.joshi@propsearch.com"
                ),
                Property(
                    title="Luxurious 5 BHK Villa in Lonavala (Mumbai Outskirts)",
                    city="Mumbai",
                    locality="Lonavala",
                    price=85000000,
                    type="buy",
                    property_type="house",
                    bhk=5,
                    bathrooms=5,
                    area=5500,
                    image_filename="modern_villa_bangalore.png",
                    description="Fabulous 5 BHK holiday home villa nestled in the hills of Lonavala. Large private swimming pool, terrace garden, home theatre room, bar setup, and scenic valley views.",
                    amenities="Infinity Pool, Private Garden, Home Theatre, Valley View, Bar, Parking",
                    agent_name="Rohan Joshi",
                    agent_phone="+91 98200 12347",
                    agent_email="rohan.joshi@propsearch.com"
                ),
                Property(
                    title="Luxury 2 BHK Apartment in Prabhadevi",
                    city="Mumbai",
                    locality="Prabhadevi",
                    price=120000,
                    type="rent",
                    property_type="flat",
                    bhk=2,
                    bathrooms=2,
                    area=1100,
                    image_filename="luxury_apartment_mumbai.png",
                    description="High-rise apartment overlooking the Prabhadevi seashore. Features imported fittings, spacious balconies, and modular configuration.",
                    amenities="Sea View, Gym, Pool, Elevator, Parking, 24x7 Security",
                    agent_name="Neha Shah",
                    agent_phone="+91 98200 12346",
                    agent_email="neha.shah@propsearch.com"
                ),
                Property(
                    title="Cozy 1 BHK Flat in Kandivali West",
                    city="Mumbai",
                    locality="Kandivali West",
                    price=28000,
                    type="rent",
                    property_type="flat",
                    bhk=1,
                    bathrooms=1,
                    area=600,
                    image_filename="cozy_flat_interior.png",
                    description="Sleek and well-ventilated 1 BHK flat. Ideal for working couples, located in a quiet residential township.",
                    amenities="Parking, Lift, Security, Intercom, Gas Pipeline",
                    agent_name="Rohan Joshi",
                    agent_phone="+91 98200 12347",
                    agent_email="rohan.joshi@propsearch.com"
                ),
                Property(
                    title="Premium 3 BHK Flat in Ghatkopar East",
                    city="Mumbai",
                    locality="Ghatkopar East",
                    price=75000,
                    type="rent",
                    property_type="flat",
                    bhk=3,
                    bathrooms=3,
                    area=1400,
                    image_filename="luxury_apartment_mumbai.png",
                    description="Spacious semi-furnished 3 BHK flat. Excellent modular kitchen and cupboard fittings. Near Central Line railway station.",
                    amenities="Parking, Lift, Security, Power Backup, Kids Play Area",
                    agent_name="Vikram Mehta",
                    agent_phone="+91 98200 12345",
                    agent_email="vikram.mehta@propsearch.com"
                ),
                Property(
                    title="Elegant 2 BHK Flat in Thane West",
                    city="Mumbai",
                    locality="Thane West",
                    price=38000,
                    type="rent",
                    property_type="flat",
                    bhk=2,
                    bathrooms=2,
                    area=950,
                    image_filename="cozy_flat_interior.png",
                    description="Modern 2 BHK flat in Thane. Gated township, landscaped gardens, close connectivity to Eastern Express Highway.",
                    amenities="Parking, Lift, Gym, Security, Club House, Power Backup",
                    agent_name="Vikram Mehta",
                    agent_phone="+91 98200 12345",
                    agent_email="vikram.mehta@propsearch.com"
                ),
                Property(
                    title="Premium 2 BHK Apartment in Lower Parel",
                    city="Mumbai",
                    locality="Lower Parel",
                    price=26000000,
                    type="buy",
                    property_type="flat",
                    bhk=2,
                    bathrooms=2,
                    area=950,
                    image_filename="luxury_apartment_mumbai.png",
                    description="Luxury flat in a high-rise tower in Lower Parel. Modern interiors, high-performance building infrastructure.",
                    amenities="Gym, Pool, Clubhouse, Lift, Covered Parking, Security",
                    agent_name="Neha Shah",
                    agent_phone="+91 98200 12346",
                    agent_email="neha.shah@propsearch.com"
                ),
                Property(
                    title="Stunning 3 BHK Flat in Colaba",
                    city="Mumbai",
                    locality="Colaba",
                    price=75000000,
                    type="buy",
                    property_type="flat",
                    bhk=3,
                    bathrooms=3,
                    area=1800,
                    image_filename="luxury_penthouse.png",
                    description="Sea-facing heritage style 3 BHK flat in Colaba. Completely updated modern kitchen and luxury marble floors.",
                    amenities="Sea View, Parking, Elevator, Security, Concierge",
                    agent_name="Vikram Mehta",
                    agent_phone="+91 98200 12345",
                    agent_email="vikram.mehta@propsearch.com"
                ),
                Property(
                    title="Modern 1 BHK Flat in Borivali West",
                    city="Mumbai",
                    locality="Borivali West",
                    price=8500000,
                    type="buy",
                    property_type="flat",
                    bhk=1,
                    bathrooms=1,
                    area=580,
                    image_filename="cozy_flat_interior.png",
                    description="Vastu-compliant 1 BHK flat in Borivali. Centrally located with easy access to metro links and shopping centers.",
                    amenities="Parking, Lift, Security, Power Backup, CCTV",
                    agent_name="Rohan Joshi",
                    agent_phone="+91 98200 12347",
                    agent_email="rohan.joshi@propsearch.com"
                ),
                Property(
                    title="Exclusive 4 BHK Penthouse in Mulund West",
                    city="Mumbai",
                    locality="Mulund West",
                    price=34000000,
                    type="buy",
                    property_type="flat",
                    bhk=4,
                    bathrooms=4,
                    area=2800,
                    image_filename="luxury_penthouse.png",
                    description="High-end duplex penthouse in Mulund. Massive rooms, double-height ceilings, and private terrace lounge.",
                    amenities="Skyline View, Private Terrace, Pool, Gym, Security, Parking",
                    agent_name="Neha Shah",
                    agent_phone="+91 98200 12346",
                    agent_email="neha.shah@propsearch.com"
                ),
                Property(
                    title="Elegant 3 BHK House in Navi Mumbai",
                    city="Mumbai",
                    locality="Kharghar",
                    price=19500000,
                    type="buy",
                    property_type="house",
                    bhk=3,
                    bathrooms=3,
                    area=1900,
                    image_filename="modern_villa_bangalore.png",
                    description="Independent row house in Navi Mumbai. Split levels, modular kitchen, and beautiful private terrace.",
                    amenities="Car Parking, Terrace, Garden, Security, Pet Friendly",
                    agent_name="Rohan Joshi",
                    agent_phone="+91 98200 12347",
                    agent_email="rohan.joshi@propsearch.com"
                ),
                Property(
                    title="Exclusive 4 BHK Villa in Goregaon East",
                    city="Mumbai",
                    locality="Goregaon East",
                    price=52000000,
                    type="buy",
                    property_type="house",
                    bhk=4,
                    bathrooms=4,
                    area=3200,
                    image_filename="modern_villa_bangalore.png",
                    description="Stunning luxury bungalow near Aarey Colony. Green views, private pool, and automated car stacking.",
                    amenities="Private Pool, Garden, Parking, Security, Power Backup",
                    agent_name="Neha Shah",
                    agent_phone="+91 98200 12346",
                    agent_email="neha.shah@propsearch.com"
                ),

                # --- CHENNAI PROPERTIES ---
                Property(
                    title="Elegant 2 BHK Apartment in Adyar",
                    city="Chennai",
                    locality="Adyar",
                    price=32000,
                    type="rent",
                    property_type="flat",
                    bhk=2,
                    bathrooms=2,
                    area=1100,
                    image_filename="cozy_flat_interior.png",
                    description="Semi-furnished spacious 2 BHK in the prime locality of Adyar. Well-ventilated rooms, covered parking, and round-the-clock security.",
                    amenities="Parking, Lift, Security, Power Backup",
                    agent_name="Suresh Kumar",
                    agent_phone="+91 98400 12345",
                    agent_email="suresh.kumar@propsearch.com"
                ),
                Property(
                    title="Modern 3 BHK Flat in OMR",
                    city="Chennai",
                    locality="OMR (Old Mahabalipuram Road)",
                    price=28000,
                    type="rent",
                    property_type="flat",
                    bhk=3,
                    bathrooms=3,
                    area=1450,
                    image_filename="luxury_apartment_mumbai.png",
                    description="Spacious 3 BHK high-rise flat on OMR IT Corridor. Features fully equipped gym, clubhouse, and regular water supply.",
                    amenities="Gym, Pool, Clubhouse, Parking, Lift, 24x7 Security",
                    agent_name="Meenakshi Sundaram",
                    agent_phone="+91 98400 12346",
                    agent_email="meenakshi.s@propsearch.com"
                ),
                Property(
                    title="Compact 1 BHK Studio in Velachery",
                    city="Chennai",
                    locality="Velachery",
                    price=16000,
                    type="rent",
                    property_type="flat",
                    bhk=1,
                    bathrooms=1,
                    area=550,
                    image_filename="cozy_flat_interior.png",
                    description="Cozy 1 BHK studio perfect for students or single working professionals. Close to Phoenix Marketcity and local train links.",
                    amenities="Parking, Security, Power Backup, AC",
                    agent_name="Suresh Kumar",
                    agent_phone="+91 98400 12345",
                    agent_email="suresh.kumar@propsearch.com"
                ),
                Property(
                    title="Luxury 4 BHK Beach Villa in ECR",
                    city="Chennai",
                    locality="ECR (East Coast Road)",
                    price=150000,
                    type="rent",
                    property_type="house",
                    bhk=4,
                    bathrooms=4,
                    area=3600,
                    image_filename="modern_villa_bangalore.png",
                    description="Spectacular independent villa on ECR. Private beach access, swimming pool, large lawn, and complete serenity.",
                    amenities="Beach Access, Private Pool, Lawn, Gym, Covered Parking, Security",
                    agent_name="Karthik Raja",
                    agent_phone="+91 98400 12347",
                    agent_email="karthik.raja@propsearch.com"
                ),
                Property(
                    title="Spacious 3 BHK House in Mylapore",
                    city="Chennai",
                    locality="Mylapore",
                    price=65000,
                    type="rent",
                    property_type="house",
                    bhk=3,
                    bathrooms=3,
                    area=1800,
                    image_filename="modern_villa_bangalore.png",
                    description="Traditional yet modern independent 3 BHK house in Mylapore. Vastu-compliant, close to Kapaleeshwarar Temple.",
                    amenities="Car Parking, Terrace access, Water Storage, Pet Friendly",
                    agent_name="Meenakshi Sundaram",
                    agent_phone="+91 98400 12346",
                    agent_email="meenakshi.s@propsearch.com"
                ),
                Property(
                    title="Premium 2 BHK Flat in T-Nagar",
                    city="Chennai",
                    locality="T-Nagar",
                    price=40000,
                    type="rent",
                    property_type="flat",
                    bhk=2,
                    bathrooms=2,
                    area=1050,
                    image_filename="luxury_apartment_mumbai.png",
                    description="Beautiful apartment located in Chennai's commercial hub. Close to shopping centers, premium restaurants, and metro links.",
                    amenities="Parking, Lift, Security, AC, Gas Pipeline",
                    agent_name="Suresh Kumar",
                    agent_phone="+91 98400 12345",
                    agent_email="suresh.kumar@propsearch.com"
                ),
                Property(
                    title="Exclusive 3 BHK Penthouse in Anna Nagar",
                    city="Chennai",
                    locality="Anna Nagar",
                    price=90000,
                    type="rent",
                    property_type="flat",
                    bhk=3,
                    bathrooms=3,
                    area=2200,
                    image_filename="luxury_penthouse.png",
                    description="Luxurious penthouse with spacious layout. Private terrace garden views, marble floors, and complete modular kitchen.",
                    amenities="Private Terrace, Gym, Clubhouse, Lift, Pool, Security",
                    agent_name="Karthik Raja",
                    agent_phone="+91 98400 12347",
                    agent_email="karthik.raja@propsearch.com"
                ),
                Property(
                    title="Cozy 1 BHK Flat in Nungambakkam",
                    city="Chennai",
                    locality="Nungambakkam",
                    price=24000,
                    type="rent",
                    property_type="flat",
                    bhk=1,
                    bathrooms=1,
                    area=650,
                    image_filename="cozy_flat_interior.png",
                    description="Semi-furnished 1 BHK in Nungambakkam. Close to college hubs, corporate offices, and central metro access.",
                    amenities="Parking, Lift, Security, Power Backup",
                    agent_name="Meenakshi Sundaram",
                    agent_phone="+91 98400 12346",
                    agent_email="meenakshi.s@propsearch.com"
                ),
                Property(
                    title="Charming 2 BHK House in Besant Nagar",
                    city="Chennai",
                    locality="Besant Nagar",
                    price=45000,
                    type="rent",
                    property_type="house",
                    bhk=2,
                    bathrooms=2,
                    area=1200,
                    image_filename="modern_villa_bangalore.png",
                    description="Charming independent house close to Elliot's Beach in Besant Nagar. Features private terrace and green lawn space.",
                    amenities="Beach access, Terrace, Private Parking, Pet Friendly",
                    agent_name="Karthik Raja",
                    agent_phone="+91 98400 12347",
                    agent_email="karthik.raja@propsearch.com"
                ),
                Property(
                    title="Premium 3 BHK Flat in Sholinganallur",
                    city="Chennai",
                    locality="Sholinganallur",
                    price=30000,
                    type="rent",
                    property_type="flat",
                    bhk=3,
                    bathrooms=3,
                    area=1500,
                    image_filename="luxury_apartment_mumbai.png",
                    description="Modern 3 BHK apartment in an integrated township in Sholinganallur. Complete modular wardrobes, lift, and play area.",
                    amenities="Parking, Lift, Security, Play Zone, Clubhouse, Power Backup",
                    agent_name="Suresh Kumar",
                    agent_phone="+91 98400 12345",
                    agent_email="suresh.kumar@propsearch.com"
                ),
                Property(
                    title="Ready-to-move 2 BHK Flat in Medavakkam",
                    city="Chennai",
                    locality="Medavakkam",
                    price=5500000,
                    type="buy",
                    property_type="flat",
                    bhk=2,
                    bathrooms=2,
                    area=950,
                    image_filename="cozy_flat_interior.png",
                    description="Vastu-compliant 2 BHK apartment in Medavakkam. Ready to occupy, semi-furnished kitchen, and excellent location.",
                    amenities="Parking, Lift, Security, Power Backup, CCTV",
                    agent_name="Meenakshi Sundaram",
                    agent_phone="+91 98400 12346",
                    agent_email="meenakshi.s@propsearch.com"
                ),
                Property(
                    title="High-Rise 3 BHK Flat in Anna Nagar",
                    city="Chennai",
                    locality="Anna Nagar",
                    price=19000000,
                    type="buy",
                    property_type="flat",
                    bhk=3,
                    bathrooms=3,
                    area=1650,
                    image_filename="luxury_apartment_mumbai.png",
                    description="Luxury high-rise flat in Anna Nagar. High-end wood paneling, designer ceilings, and spacious modular configurations.",
                    amenities="Pool, Gym, Lift, Clubhouse, Covered Parking, Security",
                    agent_name="Karthik Raja",
                    agent_phone="+91 98400 12347",
                    agent_email="karthik.raja@propsearch.com"
                ),
                Property(
                    title="Luxurious 4 BHK Beach Villa in ECR",
                    city="Chennai",
                    locality="ECR (East Coast Road)",
                    price=38000000,
                    type="buy",
                    property_type="house",
                    bhk=4,
                    bathrooms=4,
                    area=3500,
                    image_filename="modern_villa_bangalore.png",
                    description="Stunning luxury bungalow near ECR shoreline. Private swimming pool, landscaped lawn, and premium woodwork.",
                    amenities="Private Pool, Private Lawn, Sea View, Security, Parking",
                    agent_name="Karthik Raja",
                    agent_phone="+91 98400 12347",
                    agent_email="karthik.raja@propsearch.com"
                ),
                Property(
                    title="Spacious 3 BHK House in Velachery",
                    city="Chennai",
                    locality="Velachery",
                    price=12500000,
                    type="buy",
                    property_type="house",
                    bhk=3,
                    bathrooms=3,
                    area=1800,
                    image_filename="modern_villa_bangalore.png",
                    description="Independent 3 BHK villa with private terrace and covered car parking in a gated society.",
                    amenities="Terrace, Car Parking, Security, Water Harvesting, Pet Friendly",
                    agent_name="Meenakshi Sundaram",
                    agent_phone="+91 98400 12346",
                    agent_email="meenakshi.s@propsearch.com"
                ),
                Property(
                    title="Minimalist 1 BHK Flat in OMR",
                    city="Chennai",
                    locality="OMR (Old Mahabalipuram Road)",
                    price=3500000,
                    type="buy",
                    property_type="flat",
                    bhk=1,
                    bathrooms=1,
                    area=520,
                    image_filename="cozy_flat_interior.png",
                    description="Compact and stylish studio flat inside a gated project. Extremely convenient for IT techies working on OMR.",
                    amenities="Parking, Lift, Security, Power Backup, Gym",
                    agent_name="Suresh Kumar",
                    agent_phone="+91 98400 12345",
                    agent_email="suresh.kumar@propsearch.com"
                ),
                Property(
                    title="Compact 2 BHK Apartment in Tambaram",
                    city="Chennai",
                    locality="Tambaram",
                    price=4800000,
                    type="buy",
                    property_type="flat",
                    bhk=2,
                    bathrooms=2,
                    area=900,
                    image_filename="cozy_flat_interior.png",
                    description="Affordable 2 BHK flat for sale in Tambaram. Centrally located with easy access to railway station and schools.",
                    amenities="Parking, Lift, Security, CCTV, Water Storage",
                    agent_name="Meenakshi Sundaram",
                    agent_phone="+91 98400 12346",
                    agent_email="meenakshi.s@propsearch.com"
                ),
                Property(
                    title="Ultra-Premium 3 BHK Flat in Nungambakkam",
                    city="Chennai",
                    locality="Nungambakkam",
                    price=23000000,
                    type="buy",
                    property_type="flat",
                    bhk=3,
                    bathrooms=3,
                    area=1800,
                    image_filename="luxury_apartment_mumbai.png",
                    description="Exquisite designer flat off Khader Nawaz Khan Road. Premium Italian marble and luxury woodwork.",
                    amenities="Gym, Lift, Concierge, Intercom, Parking, Automated Security",
                    agent_name="Suresh Kumar",
                    agent_phone="+91 98400 12345",
                    agent_email="suresh.kumar@propsearch.com"
                ),
                Property(
                    title="Luxury 4 BHK Penthouse in Adyar",
                    city="Chennai",
                    locality="Adyar",
                    price=29000000,
                    type="buy",
                    property_type="flat",
                    bhk=4,
                    bathrooms=4,
                    area=2800,
                    image_filename="luxury_penthouse.png",
                    description="Double-height ceiling duplex penthouse in Adyar. Private terrace deck, skyline views, and smart home controls.",
                    amenities="Skyline view, Private Terrace, Lift, Pool, Gym, Security",
                    agent_name="Karthik Raja",
                    agent_phone="+91 98400 12347",
                    agent_email="karthik.raja@propsearch.com"
                ),
                Property(
                    title="Modern 3 BHK Row House in Perungudi",
                    city="Chennai",
                    locality="Perungudi",
                    price=14500000,
                    type="buy",
                    property_type="house",
                    bhk=3,
                    bathrooms=3,
                    area=2000,
                    image_filename="modern_villa_bangalore.png",
                    description="Corner row-house in a quiet gated community. Close to IT tech parks and international schools.",
                    amenities="Security, Covered Parking, Gym, Play Area, Power Backup",
                    agent_name="Meenakshi Sundaram",
                    agent_phone="+91 98400 12346",
                    agent_email="meenakshi.s@propsearch.com"
                ),
                Property(
                    title="Cozy 2 BHK Flat in Porur",
                    city="Chennai",
                    locality="Porur",
                    price=6500000,
                    type="buy",
                    property_type="flat",
                    bhk=2,
                    bathrooms=2,
                    area=1000,
                    image_filename="cozy_flat_interior.png",
                    description="Nice 2 BHK flat near Porur Junction. Centrally located, easy connectivity to DLF IT Park.",
                    amenities="Parking, Lift, Security, CCTV, Kids Play Area",
                    agent_name="Suresh Kumar",
                    agent_phone="+91 98400 12345",
                    agent_email="suresh.kumar@propsearch.com"
                ),

                # --- HYDERABAD PROPERTIES ---
                Property(
                    title="Modern 3 BHK Flat in Gachibowli",
                    city="Hyderabad",
                    locality="Gachibowli",
                    price=48000,
                    type="rent",
                    property_type="flat",
                    bhk=3,
                    bathrooms=3,
                    area=1800,
                    image_filename="luxury_apartment_mumbai.png",
                    description="Fully furnished 3 BHK high-rise flat close to major IT hubs in Gachibowli. Gated community with top amenities.",
                    amenities="Parking, Lift, Gym, Pool, Security, Power Backup",
                    agent_name="Venkat Rao",
                    agent_phone="+91 98660 12345",
                    agent_email="venkat.rao@propsearch.com"
                ),
                Property(
                    title="Cozy 2 BHK Flat in Madhapur",
                    city="Hyderabad",
                    locality="Madhapur",
                    price=35000,
                    type="rent",
                    property_type="flat",
                    bhk=2,
                    bathrooms=2,
                    area=1200,
                    image_filename="cozy_flat_interior.png",
                    description="Beautiful, semi-furnished 2 BHK apartment in Madhapur. Located in a friendly locality, close to schools and malls.",
                    amenities="Parking, Lift, Security, Power Backup",
                    agent_name="Anitha Reddy",
                    agent_phone="+91 98660 12346",
                    agent_email="anitha.reddy@propsearch.com"
                ),
                Property(
                    title="Sleek 1 BHK Studio in Kondapur",
                    city="Hyderabad",
                    locality="Kondapur",
                    price=20000,
                    type="rent",
                    property_type="flat",
                    bhk=1,
                    bathrooms=1,
                    area=650,
                    image_filename="cozy_flat_interior.png",
                    description="Minimalist 1 BHK flat perfect for IT executives. Close to Manyata Tech Park equivalents and local parks.",
                    amenities="Parking, Security, Power Backup, Elevator, AC",
                    agent_name="Venkat Rao",
                    agent_phone="+91 98660 12345",
                    agent_email="venkat.rao@propsearch.com"
                ),
                Property(
                    title="Luxury 4 BHK Villa in Jubilee Hills",
                    city="Hyderabad",
                    locality="Jubilee Hills",
                    price=220000,
                    type="rent",
                    property_type="house",
                    bhk=4,
                    bathrooms=4,
                    area=4200,
                    image_filename="modern_villa_bangalore.png",
                    description="Stunning independent bungalow in the highly premium Jubilee Hills. Features private lawn, servants quarters, and private security post.",
                    amenities="Private Pool, Lawn, Gym, Servant Quarter, Parking, Security",
                    agent_name="Srinivas Naidu",
                    agent_phone="+91 98660 12347",
                    agent_email="srinivas.n@propsearch.com"
                ),
                Property(
                    title="Spacious 3 BHK House in Banjara Hills",
                    city="Hyderabad",
                    locality="Banjara Hills",
                    price=95000,
                    type="rent",
                    property_type="house",
                    bhk=3,
                    bathrooms=3,
                    area=2500,
                    image_filename="modern_villa_bangalore.png",
                    description="Elegant independent 3 BHK bungalow in Banjara Hills. High-end wood fittings, terrace access, and dedicated garage.",
                    amenities="Terrace, Car Parking, Security, Pet Friendly, Water Storage",
                    agent_name="Anitha Reddy",
                    agent_phone="+91 98660 12346",
                    agent_email="anitha.reddy@propsearch.com"
                ),
                Property(
                    title="Cozy 2 BHK Flat in Kukatpally",
                    city="Hyderabad",
                    locality="Kukatpally",
                    price=24000,
                    type="rent",
                    property_type="flat",
                    bhk=2,
                    bathrooms=2,
                    area=1100,
                    image_filename="cozy_flat_interior.png",
                    description="Clean 2 BHK flat near metro station in Kukatpally. Friendly gated community, excellent water and security layout.",
                    amenities="Parking, Lift, Security, Power Backup, CCTV",
                    agent_name="Venkat Rao",
                    agent_phone="+91 98660 12345",
                    agent_email="venkat.rao@propsearch.com"
                ),
                Property(
                    title="Premium 3 BHK Flat in Hitec City",
                    city="Hyderabad",
                    locality="Hitec City",
                    price=55000,
                    type="rent",
                    property_type="flat",
                    bhk=3,
                    bathrooms=3,
                    area=1650,
                    image_filename="luxury_apartment_mumbai.png",
                    description="Stunning apartment in Hitec City. Semi-furnished modular wardrobes, large balconies, and high-performance society.",
                    amenities="Gym, Pool, Lift, Clubhouse, Covered Parking, Security",
                    agent_name="Srinivas Naidu",
                    agent_phone="+91 98660 12347",
                    agent_email="srinivas.n@propsearch.com"
                ),
                Property(
                    title="Charming 2 BHK House in Begumpet",
                    city="Hyderabad",
                    locality="Begumpet",
                    price=30000,
                    type="rent",
                    property_type="house",
                    bhk=2,
                    bathrooms=2,
                    area=1300,
                    image_filename="modern_villa_bangalore.png",
                    description="Charming independent house in Begumpet. Private parking, overhead water storage, and private terrace.",
                    amenities="Car Parking, Terrace, Security, Water Storage",
                    agent_name="Anitha Reddy",
                    agent_phone="+91 98660 12346",
                    agent_email="anitha.reddy@propsearch.com"
                ),
                Property(
                    title="Luxury 4 BHK Penthouse in Manikonda",
                    city="Hyderabad",
                    locality="Manikonda",
                    price=80000,
                    type="rent",
                    property_type="flat",
                    bhk=4,
                    bathrooms=4,
                    area=2800,
                    image_filename="luxury_penthouse.png",
                    description="Spacious duplex penthouse in Manikonda. Private terrace view, smart home controls, and high-performance layouts.",
                    amenities="Balcony View, Private Terrace, Lift, Gym, Pool, Security",
                    agent_name="Srinivas Naidu",
                    agent_phone="+91 98660 12347",
                    agent_email="srinivas.n@propsearch.com"
                ),
                Property(
                    title="Clean 3 BHK Flat in Miyapur",
                    city="Hyderabad",
                    locality="Miyapur",
                    price=26000,
                    type="rent",
                    property_type="flat",
                    bhk=3,
                    bathrooms=3,
                    area=1500,
                    image_filename="cozy_flat_interior.png",
                    description="Ready-to-move spacious 3 BHK flat. Quiet gated society, lift, security, and regular water supply.",
                    amenities="Parking, Lift, Security, CCTV, Power Backup",
                    agent_name="Venkat Rao",
                    agent_phone="+91 98660 12345",
                    agent_email="venkat.rao@propsearch.com"
                ),
                Property(
                    title="Premium 3 BHK Flat in Gachibowli",
                    city="Hyderabad",
                    locality="Gachibowli",
                    price=14500000,
                    type="buy",
                    property_type="flat",
                    bhk=3,
                    bathrooms=3,
                    area=1750,
                    image_filename="luxury_apartment_mumbai.png",
                    description="Beautiful 3 BHK flat in Gachibowli. Vastu-compliant design, premium wooden flooring in master bedroom.",
                    amenities="Parking, Lift, Gym, Pool, Clubhouse, 24x7 Security",
                    agent_name="Srinivas Naidu",
                    agent_phone="+91 98660 12347",
                    agent_email="srinivas.n@propsearch.com"
                ),
                Property(
                    title="Vastu-Compliant 2 BHK Flat in Kondapur",
                    city="Hyderabad",
                    locality="Kondapur",
                    price=7800000,
                    type="buy",
                    property_type="flat",
                    bhk=2,
                    bathrooms=2,
                    area=1150,
                    image_filename="cozy_flat_interior.png",
                    description="Ready-to-move-in 2 BHK flat. Features modular kitchen, modular cabinets, and dedicated covered parking.",
                    amenities="Parking, Lift, Security, Power Backup, CCTV",
                    agent_name="Venkat Rao",
                    agent_phone="+91 98660 12345",
                    agent_email="venkat.rao@propsearch.com"
                ),
                Property(
                    title="Luxury 4 BHK Villa in Jubilee Hills",
                    city="Hyderabad",
                    locality="Jubilee Hills",
                    price=95000000,
                    type="buy",
                    property_type="house",
                    bhk=4,
                    bathrooms=4,
                    area=4800,
                    image_filename="modern_villa_bangalore.png",
                    description="Stunning luxury bungalow in Jubilee Hills. Private swimming pool, landscaped lawn, and automated parking stacked.",
                    amenities="Private Pool, Private Lawn, Gym, Security, Garage",
                    agent_name="Srinivas Naidu",
                    agent_phone="+91 98660 12347",
                    agent_email="srinivas.n@propsearch.com"
                ),
                Property(
                    title="Exclusive 3 BHK Villa in Gachibowli",
                    city="Hyderabad",
                    locality="Gachibowli",
                    price=29000000,
                    type="buy",
                    property_type="house",
                    bhk=3,
                    bathrooms=3,
                    area=2800,
                    image_filename="modern_villa_bangalore.png",
                    description="Premium duplex villa in a gated township. Private lawns, wooden deck, and modern configuration.",
                    amenities="Private Garden, Parking, Security, Power Backup, Gym, Pool",
                    agent_name="Srinivas Naidu",
                    agent_phone="+91 98660 12347",
                    agent_email="srinivas.n@propsearch.com"
                ),
                Property(
                    title="Modern 3 BHK Flat in Madhapur",
                    city="Hyderabad",
                    locality="Madhapur",
                    price=16000000,
                    type="buy",
                    property_type="flat",
                    bhk=3,
                    bathrooms=3,
                    area=1900,
                    image_filename="luxury_apartment_mumbai.png",
                    description="Beautiful lake-view 3 BHK flat. Italian marble flooring, false ceilings, and smart home configuration.",
                    amenities="Lake view, Gym, Pool, Clubhouse, Covered Parking, Security",
                    agent_name="Anitha Reddy",
                    agent_phone="+91 98660 12346",
                    agent_email="anitha.reddy@propsearch.com"
                ),
                Property(
                    title="Cozy 2 BHK Flat in Miyapur",
                    city="Hyderabad",
                    locality="Miyapur",
                    price=5200000,
                    type="buy",
                    property_type="flat",
                    bhk=2,
                    bathrooms=2,
                    area=1050,
                    image_filename="cozy_flat_interior.png",
                    description="Great 2 BHK apartment for sale in Miyapur. Close to shopping centers and local train connectivity.",
                    amenities="Parking, Lift, Security, CCTV, Water Storage",
                    agent_name="Venkat Rao",
                    agent_phone="+91 98660 12345",
                    agent_email="venkat.rao@propsearch.com"
                ),
                Property(
                    title="Charming 1 BHK Studio in Begumpet",
                    city="Hyderabad",
                    locality="Begumpet",
                    price=4200000,
                    type="buy",
                    property_type="flat",
                    bhk=1,
                    bathrooms=1,
                    area=580,
                    image_filename="cozy_flat_interior.png",
                    description="Affordable and compact 1 BHK flat in Begumpet. Close to corporate tech parks and metro station.",
                    amenities="Parking, Lift, Security, Power Backup",
                    agent_name="Anitha Reddy",
                    agent_phone="+91 98660 12346",
                    agent_email="anitha.reddy@propsearch.com"
                ),
                Property(
                    title="Stunning 4 BHK Penthouse in Hitec City",
                    city="Hyderabad",
                    locality="Hitec City",
                    price=32000000,
                    type="buy",
                    property_type="flat",
                    bhk=4,
                    bathrooms=4,
                    area=3200,
                    image_filename="luxury_penthouse.png",
                    description="High-end duplex penthouse in Hitec City. Panoramic skyline views, smart home controls, and private terrace lounge.",
                    amenities="Skyline view, Private Terrace, Pool, Gym, Security, Parking",
                    agent_name="Srinivas Naidu",
                    agent_phone="+91 98660 12347",
                    agent_email="srinivas.n@propsearch.com"
                ),
                Property(
                    title="Modern 3 BHK House in Kukatpally",
                    city="Hyderabad",
                    locality="Kukatpally",
                    price=11500000,
                    type="buy",
                    property_type="house",
                    bhk=3,
                    bathrooms=3,
                    area=1700,
                    image_filename="modern_villa_bangalore.png",
                    description="Elegant independent villa in Kukatpally. Dedicated parking space, terrace access, and security guard.",
                    amenities="Car Parking, Terrace, Garden, Security, Pet Friendly",
                    agent_name="Venkat Rao",
                    agent_phone="+91 98660 12345",
                    agent_email="venkat.rao@propsearch.com"
                ),
                Property(
                    title="Ready-to-move 2 BHK Flat in Ameerpet",
                    city="Hyderabad",
                    locality="Ameerpet",
                    price=6500000,
                    type="buy",
                    property_type="flat",
                    bhk=2,
                    bathrooms=2,
                    area=1000,
                    image_filename="cozy_flat_interior.png",
                    description="Vastu-compliant 2 BHK flat. Located in a prime residential locality, close to markets and public transport.",
                    amenities="Parking, Lift, Security, CCTV, Kids Play Area",
                    agent_name="Venkat Rao",
                    agent_phone="+91 98660 12345",
                    agent_email="venkat.rao@propsearch.com"
                )
            ]
            for p in mock_properties:
                p.owner_id = admin.id
            db.bulk_save_objects(mock_properties)
            db.commit()
            print(f"Successfully seeded database with {len(mock_properties)} properties!")
        else:
            print("Database already contains properties. Seeding skipped.")
    except Exception as e:
        db.rollback()
        print(f"Error seeding database: {e}")
    finally:
        db.close()
